# Generated by Django 3.0.5 on 2020-05-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
