# Generated by Django 3.0.5 on 2020-05-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_surveyresult_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='description',
        ),
    ]
