# Generated by Django 3.0.5 on 2020-05-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_remove_files_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='UpFiles',
        ),
    ]
